// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: storage_gc_roots.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const getStorageGCRoots = `-- name: GetStorageGCRoots :many
SELECT DISTINCT r.build_id::uuid AS build_id
FROM (
    -- 1. What a spawn or a resume resolves to, for every template and every
    -- tag. This mirrors GetTemplateWithBuildByTag exactly: newest 'ready'
    -- assignment per (env, tag). It covers source='template', 'snapshot' (a
    -- paused sandbox's snapshot env) and 'snapshot_template' uniformly.
    --
    -- For a paused sandbox that is its newest snapshot, and only that one. A
    -- pause writes a self-contained memfile, so the newest snapshot holds the
    -- sandbox's whole RAM image; its rootfs header still maps blocks to every
    -- earlier snapshot's rootfs diff, and storage GC keeps those through the
    -- header, file by file. Rooting every earlier snapshot as well would pin a
    -- guest-sized memfile per pause until the sandbox is killed. While a pause
    -- is in flight, or after one failed, the newest ready snapshot is still the
    -- previous one, so it stays rooted here.
    SELECT latest.build_id
    FROM (
        SELECT DISTINCT ON (eba.env_id, eba.tag) eba.build_id
        FROM public.env_build_assignments eba
        JOIN public.env_builds eb ON eb.id = eba.build_id AND eb.status_group = 'ready'
        ORDER BY eba.env_id, eba.tag, eba.created_at DESC
    ) latest

    UNION

    -- 2. Persistent snapshot templates.
    SELECT st.build_id
    FROM public.snapshot_templates st
    WHERE st.build_id IS NOT NULL

    UNION

    -- 3. In-flight builds, which nothing else references yet. A pause build
    -- ('snapshotting') is in flight only while its pause can still finish it:
    -- the API bounds a pause by PauseTimeout (10 min,
    -- api/internal/orchestrator/pause_instance.go) and marks it failed when it
    -- does not finish, so one older than that plus a margin was abandoned (the
    -- API restarted mid-pause). One whose env is gone, so no assignment is left
    -- (the sandbox was killed), is dead as well.
    SELECT eb.id
    FROM public.env_builds eb
    WHERE eb.status_group IN ('pending', 'in_progress')
      AND (
          eb.status <> 'snapshotting'
          OR (
              eb.created_at > now() - interval '20 minutes'
              AND EXISTS (
                  SELECT 1
                  FROM public.env_build_assignments eba
                  WHERE eba.build_id = eb.id
              )
          )
      )

    UNION

    SELECT atb.build_id
    FROM public.active_template_builds atb
) r
`

// Every build the registry considers live, for template-storage GC.
//
// Storage GC keeps a build's rootfs and memfile, each on its own, only if it is
// reachable, through header block mappings, from one of these. Anything left
// out is deleted, so each clause below is a safety property rather than an
// optimisation.
func (q *Queries) GetStorageGCRoots(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getStorageGCRoots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var build_id uuid.UUID
		if err := rows.Scan(&build_id); err != nil {
			return nil, err
		}
		items = append(items, build_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
